### ISSUE TITLE
InventoryClickEvent error

### ISSUE THREAD

**Issue by myavuzokumus** [Guillaume-Lebegue/IslandUpgrades#11]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/86576034-d9433180-bf80-11ea-8ecd-a5253857e193.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/86576059-e19b6c80-bf80-11ea-98bc-31f7d1a23c20.png)

**Comment by Guillaume-Lebegue** [comment]
Well, I didn't yet look for compatibility with 1.16.

I will look for the compatibility after I have finished my other task.

**Comment by BONNe** [comment]
It looks like there is '-' (negative) cost applied to some upgrade.

**Comment by Guillaume-Lebegue** [comment]
Oh, yes, for the money cost. What is your configuration ?

**Comment by myavuzokumus** [comment]
[config.zip](https://github.com/BentoBoxWorld/Upgrades/files/4877873/config.zip)

**Comment by Guillaume-Lebegue** [comment]
Which upgrade is doing this bug? All?

**Comment by myavuzokumus** [comment]
Island levels drop when they break their islands completely. Multiply by the number you want, but it will be - as it will be the price.

[numberPlayer]*[islandLevel]*[level]*50

if islandlevel its -3 or anythink it will be - cost.

**Comment by Guillaume-Lebegue** [comment]
Oh right, sometimes level return negative level. I guess I'll add a check to set a default level to 1

**Comment by Guillaume-Lebegue** [comment]
I have set a default island level to 0. Like the level addon on default.

So be careful, using * with island level may result in 0
