### ISSUE TITLE
Range upgrade still visible in GUI even if disabled in config

### ISSUE THREAD

**Issue by MarkusLee626** [Guillaume-Lebegue/IslandUpgrades#13]
#### Describe the bug
Disabling the range upgrade in config does not disable range upgrade in GUI, although it does show up as "Max level reached"

#### Steps to reproduce the behavior

1. Install Upgrades
2. Remove range upgrade section in config
3. Reload addon
4. Do /is upgrade

#### Expected behavior

The icon for range upgrade should be disabled if the range upgrade is disabled in config

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/25385344/87255840-c1a80380-c4c0-11ea-889f-a093b32ab1c5.png)

##### Output of `/bbox version` (Mandatory)

```
12.07 16:18:27 [Server] Server thread/INFO Running SPIGOT 1.15.2.
12.07 16:18:27 [Server] Server thread/INFO BentoBox version: 1.13.1
12.07 16:18:27 [Server] Server thread/INFO Database: JSON
12.07 16:18:27 [Server] Server thread/INFO Loaded Game Worlds:
12.07 16:18:27 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
12.07 16:18:27 [Server] Server thread/INFO Loaded Addons:
12.07 16:18:27 [Server] Server thread/INFO Biomes 1.7.0 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO BSkyBlock 1.13.1 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO Challenges 0.8.2 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO ControlPanel 1.7.0 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO DimensionalTrees 1.6.0 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO Level 2.0.0 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO Limits 1.12.1 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO Upgrades 0.2.0-SNAPSHOT-b57 (ENABLED)
12.07 16:18:27 [Server] Server thread/INFO Warps 1.9.5 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by Guillaume-Lebegue** [comment]
Can you test that ?

**Comment by MarkusLee626** [comment]
![image](https://user-images.githubusercontent.com/25385344/87310866-20b55900-c551-11ea-8a58-327acb3a1b7c.png)
Uploaded the new version and reloaded bbox. Doesn't work.

**Comment by Guillaume-Lebegue** [comment]
Oops, My bad.

Should work now.

**Comment by MarkusLee626** [comment]
Brilliant, that worked. Thank you!
