### ISSUE TITLE
More translation options

### ISSUE THREAD

**Issue by Kesims** [Guillaume-Lebegue/IslandUpgrades#16]
### Description
Hello, I just want to ask if you could add an option to translate message when player buys the upgrade

For example this one:
![2020-07-22_22 08 59](https://user-images.githubusercontent.com/43478239/88223727-366d0180-cc68-11ea-87cf-06d88808904e.png)

Thanks!

**Comment by charlyg31** [comment]
plugins/BentoBox/locales/Upgrades/name_language.yml

add new .yml and copy / paste en-US.yml and translate.

![image](https://user-images.githubusercontent.com/22028655/88224432-420cf800-cc69-11ea-9988-7b1d3ced7d4f.png)

**Comment by Kesims** [comment]
Oh sorry, my bad :D I have already translated this file, and I left only this message untranslated. Thanks! :D
