### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by myavuzokumus** [Guillaume-Lebegue/IslandUpgrades#2]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/82989294-1e2f8c00-a003-11ea-8f01-cf864de5082f.png)

##### BentoBox Version (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/82989316-2b4c7b00-a003-11ea-993a-eb7e371f258c.png)

**Comment by Guillaume-Lebegue** [comment]
Hello,

Did you have an island when you used this command?

**Comment by myavuzokumus** [comment]
Hmm, yes. It gives the error only when it is out of the island.

**Comment by Guillaume-Lebegue** [comment]
Ok, so that should be fixed in the last build

**Comment by myavuzokumus** [comment]
![image](https://user-images.githubusercontent.com/47111280/83018200-8dba7100-a02d-11ea-830b-5b631501b2a7.png)

**Comment by Guillaume-Lebegue** [comment]
Well shouldn't be possible anymore, can you send a /bentobox version?

**Comment by myavuzokumus** [comment]
![image](https://user-images.githubusercontent.com/47111280/83019122-1b4a9080-a02f-11ea-98dd-d61aee9904ed.png)

**Comment by Guillaume-Lebegue** [comment]
Well, I don't see why that didn't work. For me, that had repaired the problem.

So I added one more condition for the GUI.

**Comment by myavuzokumus** [comment]
![image](https://user-images.githubusercontent.com/47111280/83116206-1e4b8c80-a0d4-11ea-93bd-881838d2ede6.png)
Keep contiunes in build 14

**Comment by Guillaume-Lebegue** [comment]
I tried to change what I use to get the island.
But if this persists, I have no more idea.

I can't really understand why this is doing that since I'm checking before running the command

**Comment by Poslovitch** [comment]
@Guillaume-Lebegue I'll have a look at this ;)

**Comment by myavuzokumus** [comment]
Ok, now working but said "You haven't island" but i only not on island, already have island.

**Comment by Guillaume-Lebegue** [comment]
Is it saying that in the console or in the chat ?

**Comment by Guillaume-Lebegue** [comment]
And are you perhaps using the command in a different world than the one with your island ?

**Comment by myavuzokumus** [comment]
1- Chat
2- Yes.

**Comment by Guillaume-Lebegue** [comment]
Ok, so that's why. I'm getting the island of the world where is the player not the one linked to the command. I'll do some modifications later to link it to the command not the player.

**Comment by tastybento** [comment]
@Guillaume-Lebegue Use `getWorld()` in composite command to auto-get the world of the command. :-)

**Comment by Guillaume-Lebegue** [comment]
Yes, but I'm looking into it and I don't think I will do it because when I change the range, I also fire the event that goes with it. But doing that, do something strange for the user that is not in its island.

And by checking that, I have also found that upgrading the range while in the spawn also do this strange thing.
So I think I will add some condition that the player need to be on his island to open the GUI.
