### ISSUE TITLE
Where is a download for this addon.

### ISSUE THREAD

**Issue by MagmaSlime123** [Guillaume-Lebegue/IslandUpgrades#33]

**Comment by tastybento** [comment]
Currently, it is only on the CI server: https://ci.bentobox.world.

**Comment by MagmaSlime123** [comment]
Ah.

**Comment by tastybento** [comment]
@Guillaume-Lebegue Do you have any objections to doing a release of this so that it gets on download.bentobox.world?

**Comment by Guillaume-Lebegue** [comment]
Well, if you could wait a little. I'll soon do a big change to settings.
