### ISSUE TITLE
RangeUpgrade permissions check does not work correctly

### ISSUE THREAD

**Issue by barpec12** [Guillaume-Lebegue/IslandUpgrades#35]
#### Describe the bug

Example permission in the config is incorrect. - https://github.com/BentoBoxWorld/Upgrades/blob/1a38e1ecdf0e67c35fac78543e0352893b9bf6f5/src/main/resources/config.yml#L18
Plugin is checking for permissions this way: https://github.com/BentoBoxWorld/Upgrades/blob/1a38e1ecdf0e67c35fac78543e0352893b9bf6f5/src/main/java/world/bentobox/upgrades/upgrades/RangeUpgrade.java#L101
and name of the RangeUpgrade is "RangeUpgrade", not "range-upgrade". - https://github.com/BentoBoxWorld/Upgrades/blob/1a38e1ecdf0e67c35fac78543e0352893b9bf6f5/src/main/java/world/bentobox/upgrades/upgrades/RangeUpgrade.java#L26

#### Expected behavior

Permissions in the config and in the code should be the same, because right now when giving permissions to the player, according to the config, player does not have possibility to upgrade his island's range.

**Comment by Guillaume-Lebegue** [comment]
Oops, you're right, however it's `rangeupgrade` since there is a .toLowerCase.

I'm fixing it in the config.
