### ISSUE TITLE
Upgrades are reset.

### ISSUE THREAD

**Issue by myavuzokumus** [Guillaume-Lebegue/IslandUpgrades#4]
#### Describe the bug
When players do the improvement, it increases properly, but after a while all records are deleted and fall to 1. I looked at all the records and it was reset to itself.

Is there an error I made in config? Or is it a addon problem? This problem is 3-4. processing. And when I delete and install the database, they upgrade from the beginning, but after a while it gets corrupted again.

Sample:
![image](https://user-images.githubusercontent.com/47111280/83394042-8e258400-a400-11ea-8cc9-d2d976dac594.png)
![image](https://user-images.githubusercontent.com/47111280/83394045-91b90b00-a400-11ea-9831-82f2c936517a.png)
![image](https://user-images.githubusercontent.com/47111280/83394095-a5fd0800-a400-11ea-810a-11eea6dee280.png)
![image](https://user-images.githubusercontent.com/47111280/83394134-b44b2400-a400-11ea-86a1-730b0591c627.png)
![image](https://user-images.githubusercontent.com/47111280/83394348-1b68d880-a401-11ea-9ad2-4016d86421fc.png)

##### BentoBox Version (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/83394295-05f3ae80-a401-11ea-82ca-4ecaec580bbf.png)

**Comment by Guillaume-Lebegue** [comment]
That is strange, do you remember having done something special before it happened ?

The only case where I'm resetting the level is when an island is deleted. Else I should only be doing increment.

Have you maybe gotten an error in the console?

**Comment by myavuzokumus** [comment]
1- No
2- No

I only restarted the server.

**Comment by Guillaume-Lebegue** [comment]
How do you stop your server ? with a command or by killing the process?

**Comment by myavuzokumus** [comment]
Command "Stop"

**Comment by Guillaume-Lebegue** [comment]
For your first picture where you show the upgrade for the bee nest, did the bug already happened?
If yes, then the level of the upgrade wasn't reset since, the island level is at 1000 so the tier 2 of the upgrade.

**Comment by myavuzokumus** [comment]
Yes, if you look at the limit pictures, the limit is still 3.

**Comment by Guillaume-Lebegue** [comment]
And it should be 5.

Are you on your island?

By the way, the database is saved when the server is closed, so if you upgraded after restarting the server, it is normal that the file doesn't show the upgrade

**Comment by myavuzokumus** [comment]
Yeah i in island.
I got this picture after turning the server off and on. If you have already noticed, there was no upgrade to the limit picture. It still stands at its normal limit.

**Comment by Guillaume-Lebegue** [comment]
Did you perhaps reset the limits database but not the upgrade database.

Else I can't reproduce it and don't see why it is doing that.

**Comment by myavuzokumus** [comment]
Ah no, I didin't reset anythink.

 I already said. This problem 3-4 times it was.

**Comment by Guillaume-Lebegue** [comment]
Found the problem.
It's coming from the limits addon.
I have made a new issue: BentoBoxWorld/Limits#83

**Comment by Guillaume-Lebegue** [comment]
And that is repaired in the last snapshot.
But you will also need the last snapshot from the limits addon
