### ISSUE TITLE
View you level on the menu

### ISSUE THREAD

**Issue by charlyg31** [Guillaume-Lebegue/IslandUpgrades#5]
Hello, in the menu, it would be nice to see that it is our upgrade level.
Thanx!

**Comment by Guillaume-Lebegue** [comment]
What do you think about adding a new line in the description?
with something like
> (level/max)

**Comment by charlyg31** [comment]
yes is good!

**Comment by charlyg31** [comment]
if it is not too late. 

```
Tier level
Level/Level max
```

**Comment by Guillaume-Lebegue** [comment]
Would something like
`Tier name (level/level max)`
on one line would be good?

I'm trying to add as little line as I can in the description.

**Comment by charlyg31** [comment]
Yes is good . Really thanx for your reactivity.

**Comment by Guillaume-Lebegue** [comment]
You can try the last Snapshot
