### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by charlyg31** [Guillaume-Lebegue/IslandUpgrades#6]
hello I propose to add a permission by tier and that one can choose a number to create a permission in the file .YML 

the permission would be for example bentobox.island.upgrade.[number]

if it is too difficult by tier we can do just one to use the /is upgrade command

![3645A8BD-2B87-436A-A0C5-E538AFF39A15](https://user-images.githubusercontent.com/22028655/85094076-20de6500-b1ee-11ea-95fe-240a4be74e2d.png)

Thanks

**Comment by Guillaume-Lebegue** [comment]
That's a good way to do it.
Do you perhaps have in mind an addon who is doing dynamic permissions like that?

**Comment by charlyg31** [comment]
Biomes addons it seems to me.

it is used with the islands on bentobox too. to give access to an island in the config in game you can create a permission.

**Comment by Guillaume-Lebegue** [comment]
Thx, I'll look at that

**Comment by Guillaume-Lebegue** [comment]
I have made an implementation. Can you try it?
